spring:
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest

custom:
  rabbit:
    first-queue: first_queue
    second-queue: second_queue
    exchange: first-exchange
    routing: rabbit.base-routing